local v = require('pink-as-fox.colors').vscode

return {
    -- Normal = { fg = v.vscFront, bg = v.vscBack },
    -- ColorColumn = { fg = 'NONE', bg = v.vscCursorDarkDark },
    -- Cursor = { fg = v.vscCursorDark, bg = v.vscCursorLight },
    -- CursorLine = { bg = v.vscCursorDarkDark },
    -- CursorColumn = { fg = 'NONE', bg = v.vscCursorDarkDark },
    -- Directory = { fg = v.vscBlue, bg = v.vscBack },
    DiffAdd = { fg = 'NONE', bg = v.vscDiffGreenLight },
    DiffChange = { fg = 'NONE', bg = v.vscDiffRedDark },
    DiffDelete = { fg = 'NONE', bg = v.vscDiffRedLight },
    DiffText = { fg = 'NONE', bg = v.vscDiffRedLight },
    EndOfBuffer = { fg = v.vscBack, bg = 'NONE' },
    ErrorMsg = { fg = v.vscRed, bg = v.vscBack },
    -- VertSplit = { fg = v.vscSplitDark, bg = v.vscBack },
    Folded = { fg = 'NONE', bg = v.vscFoldBackground },
    FoldColumn = { fg = v.vscLineNumber, bg = v.vscBack },
    SignColumn = { fg = 'NONE', bg = v.vscBack },
    IncSearch = { fg = v.vscNone, bg = v.vscSearchCurrent },
    LineNr = { fg = v.vscFront, bg = v.vscBack },
    -- CursorLineNr = { fg = v.vscPopupFront, bg = v.vscBack },
    MatchParen = { fg = v.vscNone, bg = v.vscCursorDark },
    -- ModeMsg = { fg = v.vscFront, bg = v.vscLeftDark },
    -- MoreMsg = { fg = v.vscFront, bg = v.vscLeftDark },
    -- NonText = { fg = v.vscLineNumber, bg = v.vscNone },
    -- Pmenu = { fg = v.vscPopupFront, bg = v.vscPopupBack },
    -- PmenuSel = { fg = v.vscPopupFront, bg = v.vscPopupHighlightBlue },
    -- PmenuSbar = { fg = 'NONE', bg = v.vscPopupHighlightGray },
    -- PmenuThumb = { fg = 'NONE', bg = v.vscPopupFront },
    -- Question = { fg = v.vscBlue, bg = v.vscBack },
    -- Search = { fg = v.vscNone, bg = v.vscSearch },
    -- SpecialKey = { fg = v.vscBlue, bg = v.vscNone },
    -- StatusLine = { fg = v.vscFront, bg = v.vscLeftMid },
    -- StatusLineNC = { fg = v.vscFront, bg = opts.transparent and v.vscBack or v.vscLeftDark },
    TabLine = { fg = v.vscFront, bg = v.vscTabOther },
    TabLineFill = { fg = v.vscFront, bg = v.vscTabOutside },
    TabLineSel = { fg = v.vscFront, bg = v.vscTabCurrent },
    Title = { fg = v.vscNone, bg = v.vscNone, bold = true },
    -- Visual = { fg = v.vscNone, bg = v.vscSelection },
    VisualNOS = { fg = v.vscNone, bg = v.vscSelection },
    WarningMsg = { fg = v.vscRed, bg = v.vscBack, bold = true },
    WildMenu = { fg = v.vscNone, bg = v.vscSelection },

    -- Gitgutter
    GitGutterAdd = { fg = v.vscGreen, bg = 'NONE' },
    GitGutterChange = { fg = v.vscYellow, bg = 'NONE' },
    GitGutterDelete = { fg = v.vscRed, bg = 'NONE' },

    -- Git Signs
    GitSignsAdd = { fg = v.vscGreen, bg = 'NONE' },
    GitSignsChange = { fg = v.vscYellow, bg = 'NONE' },
    GitSignsDelete = { fg = v.vscRed, bg = 'NONE' },
    GitSignsAddLn = { fg = v.vscBack, bg = v.vscGreen },
    GitSignsChangeLn = { fg = v.vscBack, bg = v.vscYellow },
    GitSignsDeleteLn = { fg = v.vscBack, bg = v.vscRed },

    -- -- NvimTree
    -- NvimTreeRootFolder = { fg = v.vscFront, bg = 'NONE', bold = true },
    -- NvimTreeGitDirty = { fg = v.vscYellow, bg = 'NONE' },
    -- NvimTreeGitNew = { fg = v.vscGreen, bg = 'NONE' },
    -- NvimTreeImageFile = { fg = v.vscViolet, bg = 'NONE' },
    -- NvimTreeEmptyFolderName = { fg = v.vscGray, bg = 'NONE' },
    -- NvimTreeFolderName = { fg = v.vscFront, bg = 'NONE' },
    -- NvimTreeSpecialFile = { fg = v.vscPink, bg = 'NONE', underline = true },
    -- NvimTreeNormal = { fg = v.vscFront, bg = opts.disable_nvimtree_bg and v.vscBack or v.vscLeftDark },
    -- NvimTreeCursorLine = { fg = 'NONE', bg = opts.disable_nvimtree_bg and v.vscCursorDarkDark or v.vscLeftMid },
    -- NvimTreeVertSplit = { fg = opts.disable_nvimtree_bg and v.vscSplitDark or v.vscBack, bg = v.vscBack },
    -- NvimTreeEndOfBuffer = { fg = opts.disable_nvimtree_bg and v.vscCursorDarkDark or v.vscLeftDark },
    -- NvimTreeOpenedFolderName = { fg = 'NONE', bg = opts.disable_nvimtree_bg and v.vscCursorDarkDark or v.vscLeftDark },
    -- NvimTreeGitRenamed = { fg = v.vscGitRenamed, bg = 'NONE' },
    -- NvimTreeGitIgnored = { fg = v.vscGitIgnored, bg = 'NONE' },
    -- NvimTreeGitDeleted = { fg = v.vscGitDeleted, bg = 'NONE' },
    -- NvimTreeGitStaged = { fg = v.vscGitStageModified, bg = 'NONE' },
    -- NvimTreeGitMerge = { fg = v.vscGitUntracked, bg = 'NONE' },
    -- NvimTreeGitDirty = { fg = v.vscGitModified, bg = 'NONE' },
    -- NvimTreeGitNew = { fg = v.vscGitAdded, bg = 'NONE' },

    -- -- Bufferline
    -- BufferLineIndicatorSelected = { fg = v.vscLeftDark, bg = 'NONE' },
    -- BufferLineFill = { fg = 'NONE', bg = opts.transparent and v.vscBack or v.vscLeftDark },

    -- BarBar
    BufferCurrent = { fg = v.vscFront, bg = v.vscTabCurrent },
    BufferCurrentIndex = { fg = v.vscFront, bg = v.vscTabCurrent },
    BufferCurrentMod = { fg = v.vscYellowOrange, bg = v.vscTabCurrent },
    BufferCurrentSign = { fg = v.vscFront, bg = v.vscTabCurrent },
    BufferCurrentTarget = { fg = v.vscRed, bg = v.vscTabCurrent },
    BufferVisible = { fg = v.vscGray, bg = v.vscTabCurrent },
    BufferVisibleIndex = { fg = v.vscGray, bg = v.vscTabCurrent },
    BufferVisibleMod = { fg = v.vscYellowOrange, bg = v.vscTabCurrent },
    BufferVisibleSign = { fg = v.vscGray, bg = v.vscTabCurrent },
    BufferVisibleTarget = { fg = v.vscRed, bg = v.vscTabCurrent },
    BufferInactive = { fg = v.vscGray, bg = v.vscTabOther },
    BufferInactiveIndex = { fg = v.vscGray, bg = v.vscTabOther },
    BufferInactiveMod = { fg = v.vscYellowOrange, bg = v.vscTabOther },
    BufferInactiveSign = { fg = v.vscGray, bg = v.vscTabOther },
    BufferInactiveTarget = { fg = v.vscRed, bg = v.vscTabOther },
    BufferTabpages = { fg = v.vscFront, bg = v.vscTabOther },
    BufferTabpagesFill = { fg = v.vscFront, bg = v.vscTabOther },

    -- IndentBlankLine
    IndentBlanklineContextChar = { fg = v.vscContextCurrent, bg = 'NONE', nocombine = true },
    IndentBlanklineContextStart = { sp = v.vscContextCurrent, bg = 'NONE', nocombine = true, underline = true },
    IndentBlanklineChar = { fg = v.vscContext, bg = 'NONE', nocombine = true },
    IndentBlanklineSpaceChar = { fg = v.vscContext, bg = 'NONE', nocombine = true },
    IndentBlanklineSpaceCharBlankline = { fg = v.vscContext, bg = 'NONE', nocombine = true },

    -- COv.nvim
    CocHighlightText = { fg = 'NONE', bg = v.vscPopupHighlightGray},
    CocHighlightRead = { fg = 'NONE', bg = v.vscPopupHighlightGray},
    CocHighlightWrite = { fg = 'NONE', bg = v.vscPopupHighlightGray},

    -- Dashboard
    DashboardHeader = { fg = v.vscBlue, bg = 'NONE' },
    DashboardDesc = { fg = v.vscYellowOrange, bg = 'NONE' },
    DashboardIcon = { fg = v.vscYellowOrange, bg = 'NONE' },
    DashboardShortCut = { fg = v.vscPink, bg = 'NONE' },
    DashboardKey = { fg = v.vscWhite, bg = 'NONE' },
    DashboardFooter = { fg = v.vscBlue, bg = 'NONE', italic = true },

    NvimTreeFolderIcon = { fg = v.vscBlue, bg = 'NONE' },
    NvimTreeIndentMarker = { fg = v.vscLineNumber, bg = 'NONE' },

    LspFloatWinNormal = { fg = v.vscFront, bg = 'NONE' },
    LspFloatWinBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaHoverBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaSignatureHelpBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaCodeActionBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaDefPreviewBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspLinesDiagBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaRenameBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaBorderTitle = { fg = v.vscCursorDark, bg = 'NONE' },
    LSPSagaDiagnosticTruncateLine = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaDiagnosticBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaDiagnosticBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaShTruncateLine = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaShTruncateLine = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaDocTruncateLine = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaRenameBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    LspSagaLspFinderBorder = { fg = v.vscLineNumber, bg = 'NONE' },

    TelescopePromptBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    TelescopeResultsBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    TelescopePreviewBorder = { fg = v.vscLineNumber, bg = 'NONE' },
    TelescopeNormal = { fg = v.vscFront, bg = 'NONE' },
    TelescopeSelection = { fg = v.vscFront, bg = v.vscPopupHighlightBlue },
    TelescopeMultiSelection = { fg = v.vscFront, bg = v.vscPopupHighlightBlue },
    TelescopeMatching = { fg = v.vscMediumBlue, bg = 'NONE', bold = true },
    TelescopePromptPrefix = { fg = v.vscFront, bg = 'NONE' },

    -- symbols-outline
    -- white fg and lualine blue bg
    FocusedSymbol = { fg = '#ffffff', bg = v.vscUiBlue },
    SymbolsOutlineConnector = { fg = v.vscLineNumber, bg = 'NONE' },
}
