local v = require('pink-as-fox.colors').vscode

return {
  -- CmpItemAbbr = { fg = p.gray[4] },
  -- CmpItemAbbrDeprecated = { fg = c.comment, style = 'strikethrough' },
  -- CmpItemAbbrMatch = { fg = p.red[3] },
  -- CmpItemAbbrMatchFuzzy = { link = 'CmpItemAbbrMatch' },
  -- CmpItemMenu = { fg = c.comment },
  -- CmpItemKind = { clear = true },
  -- CmpItemKindClass = { fg = c.type },
  -- CmpItemKindColor = { fg = p.red[3] }, --------------
  -- CmpItemKindConstant = { fg = c.constant },
  -- CmpItemKindConstructor = { fg = c.type },
  -- CmpItemKindEnum = { fg = c.type },
  -- CmpItemKindEnumMember = { fg = c.field },
  -- CmpItemKindEvent = { fg = p.red[3] }, --------------
  -- CmpItemKindField = { fg = c.field },
  -- CmpItemKindFile = { fg = c.string },
  -- CmpItemKindFolder = { fg = c.string },
  -- CmpItemKindFunction = { fg = c.method },
  -- CmpItemKindInterface = { fg = c.type },
  -- CmpItemKindKeyword = { fg = c.keyword },
  -- CmpItemKindMethod = { fg = c.method },
  -- CmpItemKindModule = { fg = c.namespace },
  -- CmpItemKindOperator = { fg = c.operator },
  -- CmpItemKindProperty = { fg = c.field },
  -- CmpItemKindReference = { fg = c.type },
  -- CmpItemKindSnippet = { fg = c.literal },
  -- CmpItemKindStruct = { fg = c.type },
  -- CmpItemKindText = { fg = c.comment },
  -- CmpItemKindTypeParameter = { fg = c.parameter },
  -- CmpItemKindUnit = { fg = p.red[3] }, --------------
  -- CmpItemKindValue = { fg = p.red[3] }, --------------
  -- CmpItemKindVariable = { fg = c.variable },

  CmpItemKindVariable = { fg = v.vscLightBlue, bg = 'NONE' },
  CmpItemKindInterface = { fg = v.vscLightBlue, bg = 'NONE' },
  CmpItemKindText = { fg = v.vscLightBlue, bg = 'NONE' },
  CmpItemKindFunction = { fg = v.vscPink, bg = 'NONE' },
  CmpItemKindMethod = { fg = v.vscPink, bg = 'NONE' },
  CmpItemKindKeyword = { fg = v.vscFront, bg = 'NONE' },
  CmpItemKindProperty = { fg = v.vscFront, bg = 'NONE' },
  CmpItemKindUnit = { fg = v.vscFront, bg = 'NONE' },
  CmpItemKindConstructor = { fg = v.vscUiOrange, bg = 'NONE' },
  CmpItemMenu = { fg = v.vscPopupFront, bg = 'NONE' },
  CmpItemAbbr = { fg = v.vscFront, bg = 'NONE' },
  CmpItemAbbrDeprecated = { fg = v.vscCursorDark, bg = v.vscPopupBack, strikethrough = true },
  CmpItemAbbrMatch = { fg = v.vscMediumBlue, bg = 'NONE', bold = true },
  CmpItemAbbrMatchFuzzy = { fg = v.vscMediumBlue, bg = 'NONE', bold = true },
  CmpItemKind = { link = 'Pmenu' },
  CmpItemKindClass = { link = 'CmpItemKindConstructor' },
  CmpItemKindModule = { link = 'CmpItemKindKeyword' },
  CmpItemKindOperator = { link = '@operator' },
  CmpItemKindReference = { link = '@parameter.reference' },
  CmpItemKindValue = { link = '@field' },
  CmpItemKindField = { link = '@field' },
  CmpItemKindEnum = { link = '@field' },
  CmpItemKindSnippet = { link = '@text' },
  CmpItemKindColor = { link = 'cssColor' },
  CmpItemKindFile = { link = '@text.uri' },
  CmpItemKindFolder = { link = '@text.uri' },
  CmpItemKindEvent = { link = '@constant' },
  CmpItemKindEnumMember = { link = '@field' },
  CmpItemKindConstant = { link = '@constant' },
  CmpItemKindStruct = { link = '@structure' },
  CmpItemKindTypeParameter = { link = '@parameter' },

  CompeDocumentation = { link = 'Pmenu' },
  CompeDocumentationBorder = { link = 'Pmenu' },
}
