local v = require('pink-as-fox.colors').vscode
local c = require('pink-as-fox.colors').components

return {
  -- TODO:
  -- Field = { fg = c.field },
  -- Parameter = { fg = c.parameter },
  -- Warn = { fg = c.warn },

  Namespace = { fg = v.vscBlueGreen, bg = 'NONE' },
  Comment = { fg = c.comment, bg = 'NONE', italic = true },
  Constant = { fg = v.vscBlue, bg = 'NONE' },
  String = { fg = v.vscOrange, bg = 'NONE' },
  Character = { fg = v.vscOrange, bg = 'NONE' },
  Number = { fg = v.vscLightGreen, bg = 'NONE' },
  Boolean = { fg = v.vscBlue, bg = 'NONE' },
  Float = { fg = v.vscLightGreen, bg = 'NONE' },
  Identifier = { fg = v.vscLightBlue, bg = 'NONE' },
  Function = { fg = v.vscYellow, bg = 'NONE' },
  Statement = { fg = v.vscPink, bg = 'NONE' },
  Conditional = { fg = v.vscPink, bg = 'NONE' },
  Repeat = { fg = v.vscPink, bg = 'NONE' },
  Label = { fg = v.vscPink, bg = 'NONE' },
  Operator = { fg = v.vscFront, bg = 'NONE' },
  Keyword = { fg = v.vscPink, bg = 'NONE' },
  Exception = { fg = v.vscPink, bg = 'NONE' },
  PreProc = { fg = v.vscPink, bg = 'NONE' },
  Include = { fg = v.vscPink, bg = 'NONE' },
  Define = { fg = v.vscPink, bg = 'NONE' },
  Macro = { fg = v.vscPink, bg = 'NONE' },
  Type = { fg = v.vscBlue, bg = 'NONE' },
  StorageClass = { fg = v.vscBlue, bg = 'NONE' },
  Structure = { fg = v.vscBlueGreen, bg = 'NONE' },
  Typedef = { fg = v.vscBlue, bg = 'NONE' },
  Special = { fg = v.vscYellowOrange, bg = 'NONE' },
  SpecialChar = { fg = v.vscFront, bg = 'NONE' },
  Tag = { fg = v.vscFront, bg = 'NONE' },
  Delimiter = { fg = v.vscFront, bg = 'NONE' },
  SpecialComment = { fg = v.vscGreen, bg = 'NONE' },
  Debug = { fg = v.vscFront, bg = 'NONE' },
  Underlined = { fg = v.vscNone, bg = 'NONE', underline = true },
  Conceal = { fg = v.vscFront, bg = v.vscBack },
  Ignore = { fg = v.vscFront, bg = 'NONE' },
  Error = { fg = v.vscRed, bg = v.vscBack, undercurl = true, sp = v.vscRed },
  Todo = { fg = v.vscYellowOrange, bg = v.vscBack, bold = true },
  SpellBad = { fg = v.vscRed, bg = v.vscBack, undercurl = true, sp = v.vscRed },
  SpellCap = { fg = v.vscRed, bg = v.vscBack, undercurl = true, sp = v.vscRed },
  SpellRare = { fg = v.vscRed, bg = v.vscBack, undercurl = true, sp = v.vscRed },
  SpellLocal = { fg = v.vscRed, bg = v.vscBack, undercurl = true, sp = v.vscRed },
  Whitespace = { fg = v.vscLineNumber },
}
